Traceback (most recent call last):
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\martin\anaconda3\envs\workenv\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\martin\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from PIL import Image, ImageOps
import numpy as np
#img = Image.open("Torx_000.jpg")
#np_img = np.array(img)
#np_img.shape
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-e9f0552a7f21>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mPIL[0m [1;32mimport[0m [0mImage[0m[1;33m,[0m [0mImageOps[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[0m
[0;32m      3[0m [1;31m#img = Image.open("Torx_000.jpg")[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;31m#np_img = np.array(img)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;31m#np_img.shape[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'PIL'
ModuleNotFoundError: No module named 'PIL'

